package package1;

public class Consultas {
	public static String CONSULTA_EMPLEADOS_SALARIO_DESC="SELECT * from EMPLOYEES E, DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID ORDER BY E.SALARY DESC";
	public static String CONSULTA_SUELDO_ADMIN_20="SELECT (SALARY * 1.2)from DEPARTMENTS WHERE DEPARTMENT_ID = Administration";
}

